services:
 web:
  build:
   context: ./frontend
   dockerfile: Dockerfile
  ports:
  - "5173:5173"
  volumes:
  - ./frontend:/app/frontend
 api:
  build:
   context: ./backend
   dockerfile: Dockerfile
  ports:
  - "8787:8787"
  volumes:
  - ./backend:/app/backend